// export const CHANGE_EMAIL_ADDRESS = 'CHANGE_EMAIL_ADDRESS';

// export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

export const LOGIN_LOAD = 'LOGIN_LOAD';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_FAIL = 'LOGIN_FAIL';
